name: Format Check

on:
  push:
  pull_request:

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.200' 

      - name: Restore dependencies
        run: dotnet restore

      - name: Run dotnet format
        run: dotnet format --verify-no-changes
